try {
  throw new Error("foo")
} catch err {
  io.out(err)
}
